import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css/bundle";

const newKansas = localFont({
  src: [
    {
      path: "./fonts/NewKansas/NewKansasExtraSwash-LightItalic.woff",
      style: "italic",
      weight: "300",
    },
    {
      path: "./fonts/NewKansas/NewKansasExtraSwash-RegularItalic.woff",
      style: "italic",
    },
    {
      path: "./fonts/NewKansas/NewKansas-Light.woff",
      style: "normal",
      weight: "300",
    },
    {
      path: "./fonts/NewKansas/NewKansas-Regular.woff",
      style: "normal",
    },
    {
      path: "./fonts/NewKansas/NewKansas-Medium.woff",
      style: "normal",
      weight: "500",
    },
  ],
  variable: "--font-new-kansas",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${newKansas.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
